### ISSUE TITLE
slides方法无法将演示文稿上传上去。

### ISSUE THREAD

**Issue by YouAreALegend** [DevinY/bbb-php-api#1]
示例：
1）如果slides方法放create后面
    $meeting->create();
    $meeting->slides(['https://www.africau.edu/images/default/sample.pdf']);
进入会议后，只有默认的演示文稿。
2)如果放在create前面（我的理解应该就是放前面）
    $meeting->slides(['https://www.africau.edu/images/default/sample.pdf']);
    $meeting->create();
进入会议后，不会显示演示文稿（包括默认的也不会显示）

这个是接口问题还是bigbluebutton的问题呢？第二种情况BBB会报IOException

**Comment by DevinY** [comment]
我的API太久沒更新了，我想新的API文件如下，這一兩天有空我會補上，或是您也可以自己實做自己的呼叫。

https://docs.bigbluebutton.org/development/api/#insertdocument

**Comment by DevinY** [comment]
我目前手邊沒有新版本，我在2.6.6的環境
BigBlueButton Server 2.6.6 (1178)
同樣沒效果，感覺是BBB的問題...@@

請透過attendee()或moderator()測看看，他們都會跑create()。
slides是會以Body的方式在create的api一起送出的。

$meeting->slides($slides);

echo sprintf("<a href='%s'>Join as Student</a><br/>",$meeting->attendee("John")); //參與者
echo sprintf("<a href='%s'>Join as Teacher</a><br/>",$meeting->moderator("Devin")); //講師

**Comment by DevinY** [comment]
看起來是有人回報有問題

https://github.com/bigbluebutton/bigbluebutton/issues/16593

**Comment by DevinY** [comment]
經測試後，是遠端主機用let's encrypt憑證造成的，換成別的憑證，是可正常使用的。
您可以試看看是否可以用wget https://您的主機/myfile.pdf，在BBB主機測試進行下載您的pdf是否正常。
我想這功能應該沒問題。

**Comment by YouAreALegend** [comment]
非常感谢，我这就试一下。
